### ISSUE TITLE
stb_rect_pack firing assert

### ISSUE THREAD

**Issue by SnapperTT** [nothings/stb#1112]
I'm making a glyph atlas with stb_truetype and stb_rect_pack. Both files are fresh from the repo.

Initialising:
```
		int nNodes = mAtlasSize;
		atlas.mNodes = new stbrp_node[nNodes];			
		stbrp_init_target(&atlas.mStbRectPackCtx, mAtlasSize, mAtlasSize, atlas.mNodes, nNodes);
```
Packing:

```
		// try to pack a single glyph
		stbrp_rect r;
		r.id = *((int*) &codepoint);
		r.x = 0;
		r.y = 0;
		r.w = w;
		r.h = h;
		r.was_packed = 0;
		
		stbrp_pack_rects(&activeAtlas->mStbRectPackCtx, &r, 1);
```

When I include `stb_truetype.h` *only* it works fine, but glyphs are are packed sequentially without any optimisation. When I include `stb_rect_pack.h` things blow up:

```
0x00005555555e346f in stbrp__skyline_find_min_y (c=0x55555690dcf8, first=0x7fffffffce90, x0=952, width=14, pwaste=0x7fffffffce30)
    at src/external/include/stb/stb_rect_pack.h:301
301	   STBRP_ASSERT(node->next->x > x0); // we ended up handling this in the caller for efficiency

(gdb) bt
#0  0x00005555555e346f in stbrp__skyline_find_min_y (c=0x55555690dcf8, first=0x7fffffffce90, x0=952, width=14, pwaste=0x7fffffffce30) at src/external/include/stb/stb_rect_pack.h:301
#1  0x00005555555e36f8 in stbrp__skyline_find_best_pos (c=0x55555690dcf8, width=14, height=17) at src/external/include/stb/stb_rect_pack.h:364
#2  0x00005555555e39ab in stbrp__skyline_pack_rectangle (context=0x55555690dcf8, width=14, height=17) at src/external/include/stb/stb_rect_pack.h:447
#3  0x00005555555e3d24 in stbrp_pack_rects (context=0x55555690dcf8, rects=0x7fffffffcf60, num_rects=1) at src/external/include/stb/stb_rect_pack.h:563
...
```

Am I doing anything incorrectly? Please advise

**Comment by SnapperTT** [comment]
I found the problem:

mStbRectPackCtx is a member of a struct. The struct is stored in a vector. Something somewhere is not copied correctly. Putting the struct on the heap and storing pointers in a vector fixes it.
