### ISSUE TITLE
UBSAN: stb_ds.h `index 512 out of bounds for type 'char [8]'`

### ISSUE THREAD

**Issue by samrat** [nothings/stb#1415]
**Describe the bug**
When used with a `sh_new_arena`, `shput` leads to undefined behaviour.

**To Reproduce**
1. Example code:
```c
#define STB_DS_IMPLEMENTATION
#include "stb_ds.h"
#include <stdio.h>

typedef struct Intern {
  char *key;
  void *value;
} Intern;

static Intern *interns;

char *str_intern(const char *str) {
  Intern *intern = shgetp_null(interns, str);
  if (intern) {
    return intern->key;
  } else {
    shput(interns, str, NULL);
    return shgetp_null(interns, str)->key;
  }
}

int main(int argc, char *argv[]) {
  sh_new_arena(interns);
  printf("%s\n", str_intern("hello"));
  return 0;
}
```

2. Compile with:
```sh
clang -g -Wall -Wextra --pedantic -Wformat test_stb_ds_ubsan.c -o test_stb_ds_ubsan -fsanitize=address,undefined
```

Running this leads to the following UBSan message:

```sh
$ UBSAN_OPTIONS=print_stacktrace=1 ./test_stb_ds_ubsan
stb_ds.h:1599:27: runtime error: index 512 out of bounds for type 'char [8]'
    #0 0x1001a8570 in stbds_stralloc stb_ds.h:1599
    #1 0x1001a4200 in stbds_hmput_key stb_ds.h:1452
    #2 0x1001ab150 in str_intern test_stb_ds_ubsan.c:17
    #3 0x1001ab970 in main test_stb_ds_ubsan.c:24
    #4 0x100345084 in start+0x200 (dyld:arm64e+0x5084)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior stb_ds.h:1599:27 in
hello
```

**Comment by rygorous** [comment]
While technically UB, the particular practice in question (using an array at the end of a dynamically-allocated struct as variable-size) is fairly idiomatic in C. There might be a way to declare the structure differently to hint to UBSan that this array is intended as de-facto variable length but there's no way to fix it as such, this is working as intended.
