### ISSUE TITLE
stb_ds.h : Valgrind detects a direct memory leak

### ISSUE THREAD

**Issue by avivbeeri** [nothings/stb#1488]
Hi there,

I use stb_ds.h in a project of mine for hash maps. When I compile and run it with valgrind's memory leak checks enabled on linux, it detects a "direct leak".

```
Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4ba289 in __interceptor_realloc (BuildId: 06492acfb83cea26dc432b497c12f283ec931dab)
    #1 0x4f8863 in stbds_arrgrowf src/include/stb_ds.h:785:7
    #2 0x4f9337 in stbds_hmget_key_ts src/include/stb_ds.h:1286:9
    #3 0x4f9718 in stbds_hmget_key src/include/stb_ds.h:1315:13
```

This seems to land on this line:
`785|  b = STBDS_REALLOC(NULL, (a) ? stbds_header(a) : 0, elemsize * min_cap + sizeof(stbds_array_header));    `

I can't seem to figure out what the actual leak is, because this all seems sensible to me.

**Comment by nothings** [comment]
That's just the line it's allocated from, the leak is that it's never being freed. Are you not freeing the hashmap you're creating?

**Comment by avivbeeri** [comment]
I definitely do. Strangely, valgrind seemed satisfied after I gave the hash map a default value.

My use-case is a little complicated, so I'll try to extract a minimal reproduction when I get a chance.

**Comment by josealvim** [comment]
Had a similar problem and I can confirm that valgrind does not report a leak when I set a default value for the hash map.
I'll set try and set up a minimal example momentarily.
