### ISSUE TITLE
stb_printf.h triggers complaints from clang's Address Sanitiser

### ISSUE THREAD

**Issue by tim-rex** [nothings/stb#393]
$ cat test.c
```
#include <stdio.h>

#define STB_SPRINTF_IMPLEMENTATION
#include "../STB/stb/stb_sprintf.h"

int main (int argc, char *argv[])
{
    const unsigned int LEN = 1024;
    char str[LEN];

    printf ("Hello\n");
    stbsp_snprintf (str, LEN, "World?");
    printf ("%s\n", str);
}
```

$ clang test.c -fsanitize=address
$ ./a.out
```
Hello
=================================================================
==28032==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000102ed3584 at pc 0x000102ec10d0 bp 0x7fff5cd3dbd0 sp 0x7fff5cd3dbc8
READ of size 4 at 0x000102ed3584 thread T0
    #0 0x102ec10cf in stbsp_vsprintfcb (a.out+0x1000010cf)
    #1 0x102ecec66 in stbsp_vsnprintf (a.out+0x10000ec66)
    #2 0x102ecf50a in stbsp_snprintf (a.out+0x10000f50a)
    #3 0x102ecf709 in main (a.out+0x10000f709)
    #4 0x7fffe5f9e254 in start (libdyld.dylib+0x5254)

0x000102ed3584 is located 60 bytes to the left of global variable '<string literal>' defined in 'test.c:14:13' (0x102ed35c0) of size 4
  '<string literal>' is ascii string '%s
'
0x000102ed3587 is located 0 bytes to the right of global variable '<string literal>' defined in 'test.c:13:31' (0x102ed3580) of size 7
  '<string literal>' is ascii string 'World?'
SUMMARY: AddressSanitizer: global-buffer-overflow (a.out+0x1000010cf) in stbsp_vsprintfcb
Shadow bytes around the buggy address:
  0x1000205da660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000205da670: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000205da680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000205da690: 00 00 00 00 00 00 00 00 05 f9 f9 f9 f9 f9 f9 f9
  0x1000205da6a0: 06 f9 f9 f9 f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9
=>0x1000205da6b0:[07]f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x1000205da6c0: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x1000205da6d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000205da6e0: 00 00 00 00 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x1000205da6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f9
  0x1000205da700: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==28032==ABORTING
Abort trap: 6
```

**Comment by bullno1** [comment]
Multiple places in the code will trigger this. It's because it relies on assumption on how literal and heap allocated strings are aligned in memory and read them in 4-byte blocks. It's usually safe to do so but technically undefined behaviour to read past the string.

Everytime you see &3 in the code, it's reading single bytes to word border and start doing 4-byte reads. I've removed those checks to force it to single byte reads but then other parts of the code do things like that again so I've given up on trying to fix it for ASAN and just use something else instead (or alternatively, disable ASAN for this file).

**Comment by trex78** [comment]
Ahh, ok. In that case, it seems easy enough to disable ASAN on a per-function basis.
This does the job nicely

```
#define NO_ASAN
#if defined(__has_feature)
#  if __has_feature(address_sanitizer)
#   undef NO_ASAN
#   define NO_ASAN __attribute__((no_sanitize("address")))
#  endif
#endif

#ifdef STB_SPRINTF_STATIC
#define STBSP__PUBLICDEC static
#define STBSP__PUBLICDEF static NO_ASAN
#else
#ifdef __cplusplus
#define STBSP__PUBLICDEC extern "C"
#define STBSP__PUBLICDEF extern "C" NO_ASAN
#else
#define STBSP__PUBLICDEC extern
#define STBSP__PUBLICDEF NO_ASAN
#endif
#endif
```

**Comment by nothings** [comment]
Attempted to fix for next version but untested. (Just a minor rewrite of the suggested patch above.)

**Comment by corporateshark** [comment]
@nothings It does not.

However, this line fixes it:

```#define STBSP__ASAN __declspec(no_sanitize_address)```
