### ISSUE TITLE
heap-buffer-overflow in stbtt__find_table

### ISSUE THREAD

**Issue by khang06** [nothings/stb#618]
```
$ ./stb_truetype_asan '/home/khangaroo/afl/out/crashes/id:000000,sig:11,src:000000,op:flip1,pos:4' 
=================================================================
==23167==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61800000039c at pc 0x000000525355 bp 0x7ffc09f88e10 sp 0x7ffc09f88e08
READ of size 1 at 0x61800000039c thread T0
    #0 0x525354 in stbtt__find_table /home/khangaroo/myprojects/stb_truetype_fuzz_harness/./stb_truetype.h:1280:11
    #1 0x525354 in stbtt_InitFont_internal /home/khangaroo/myprojects/stb_truetype_fuzz_harness/./stb_truetype.h:1349
    #2 0x525354 in stbtt_InitFont /home/khangaroo/myprojects/stb_truetype_fuzz_harness/./stb_truetype.h:4736
    #3 0x52b6cc in main /home/khangaroo/myprojects/stb_truetype_fuzz_harness/main.c:26:10
    #4 0x7f94ce6cab96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #5 0x41c6f9 in _start (/home/khangaroo/myprojects/stb_truetype_fuzz_harness/stb_truetype_asan+0x41c6f9)

0x61800000039c is located 12 bytes to the right of 784-byte region [0x618000000080,0x618000000390)
allocated by thread T0 here:
    #0 0x4d1d50 in malloc (/home/khangaroo/myprojects/stb_truetype_fuzz_harness/stb_truetype_asan+0x4d1d50)
    #1 0x52b6a0 in main /home/khangaroo/myprojects/stb_truetype_fuzz_harness/main.c:19:18
    #2 0x7f94ce6cab96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/khangaroo/myprojects/stb_truetype_fuzz_harness/./stb_truetype.h:1280:11 in stbtt__find_table
Shadow bytes around the buggy address:
  0x0c307fff8020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c307fff8070: 00 00 fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==23167==ABORTING
```
[heapbufferoverflow.zip](https://github.com/nothings/stb/files/2059730/heapbufferoverflow.zip)

**Comment by nothings** [comment]
The documentation for the library was modified in 2020 to make clear it is intentionally insecure, and fixing issues like this is out of scope.
